# test parseru
CC = gcc
CFLAGS = -std=c99 -g
EXEC = parser
FILES = main.c ../error.c ../dynamic_string.c ../scanner.c ../stack.c ../symtable.c ../abstract_syntax_tree.c ../token_table.c ../expr.c ../parser.c


all:
	$(CC) $(CFLAGS) -o $(EXEC) $(FILES) -lm